export {default as HomeDashboard} from "./home/HomeDashboard"
export {default as ChangeOrderStatus} from "./changeOrderStatus/ChangeOrderStatus"
export {default as ViewProducts} from "./viewProducts/ViewProducts"
export {default as AddProduct} from "./addProduct/AddProduct"
export {default as Orders} from "./orders/Orders"
export {default as OrderDetails} from "./orderDetails/OrderDetails"